---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: techscrum
  namespace: backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: techscrum
  replicas: 2
  strategy:
   type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: techscrum
    spec:
      containers:
      - name: techscrum-backend
        image: 527423341490.dkr.ecr.ap-southeast-2.amazonaws.com/techscrum:latest 
        ports:
        - containerPort: 8000 
          protocol: TCP
        imagePullPolicy: Always
        resources:
            limits:
              cpu: 1500m
            requests:
              cpu: 1000m
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: techscrum
  namespace: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: techscrum
  minReplicas: 1 
  maxReplicas: 5
  targetCPUUtilizationPercentage: 10
---
apiVersion: v1
kind: Service
metadata:
  name: techscrum
  namespace: backend
  labels:
    app.kubernetes.io/name: techscrum
spec:
  selector:
    app.kubernetes.io/name: techscrum
  ports:
    - protocol: TCP
      port: 8000